import me.modmuss50.mpp.ReleaseType

plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.107'
    id 'idea'
    id 'eclipse'
    id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    maven {
        url "https://maven.minecraftforge.net"
    }
    maven {
        name "DynamicTrees maven"
        url "https://harleyoconnor.com/maven"
    }
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    maven {
        url "https://maven.squiddev.cc"
        content {
            includeGroup("cc.tweaked")
        }
    }
    flatDir {
        dir 'libs'
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }


        data {
            data()

            programArguments.addAll '--mod', project.mod_id, '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath(),
                    '--existing-mod', 'dynamictrees',
                    '--existing-mod', 'cobblemon'
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    // Dynamic Trees
    //implementation "com.dtteam.dynamictrees:dynamictrees-neoforge-${minecraft_version}:${dynamictrees_version}"
    //implementation "com.dtteam.dynamictreesplus:DynamicTreesPlus:${dynamictreesplus_version}"
    implementation "curse.maven:dynamictrees-252818:7206627"
    implementation "curse.maven:dynamictreesplus-478155:7205442"

    // Utilities
    runtimeOnly "curse.maven:jade-324717:6853386"
    runtimeOnly "cc.tweaked:cc-tweaked-${minecraft_version}-forge:${cc_version}"

    // Addon
    compileOnly "org.jetbrains.kotlin:kotlin-stdlib:2.0.10"
    implementation "curse.maven:kotlin-for-forge-351264:5521840"
    implementation "curse.maven:cobblemon-687131:${cobblemon_file}"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version           : minecraft_version,
            minecraft_version_range     : minecraft_version_range,
            neo_version                 : neo_version,
            loader_version_range        : loader_version_range,
            mod_id                      : mod_id,
            mod_name                    : mod_name,
            mod_display_name            : mod_display_name,
            mod_license                 : mod_license,
            mod_version                 : mod_version,
            mod_authors                 : mod_authors,
            mod_credits                 : mod_credits,
            mod_description             : mod_description,
            //mod_url                     : mod_url,
            //mod_issue_url               : mod_issue_url,
            dynamictreesversion         : dynamictrees_version,
            dynamictreesplus_version    : dynamictreesplus_version
    ]
    inputs.properties replaceProperties
    filesMatching(["META-INF/neoforge.mods.toml"]) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

def changelogFile = file("build/changelog.txt")

publishMods {
    file = jar.archiveFile
    displayName = "${mod_name.replace(' ','')}-NeoForge-${minecraft_version} ${project.version}"
    if (changelogFile.exists()) {
        changelog.set(changelogFile.getText())
    }
    type = ReleaseType.of(versionType.toUpperCase())
    modLoaders.add("neoforge")

    curseforge {
        projectId = "1060301"
        projectSlug = "dynamic-trees-cobblemon" // Required for discord webhook
        accessToken = curseApiKey ?: System.getenv("CURSEFORGE_API_KEY")
        minecraftVersions.add("1.21.1")
        requires("dynamictrees")
        requires("cobblemon")
    }
//    modrinth {
//        projectId = ""
//        accessToken = modrinthToken ?: System.getenv("MODRINTH_TOKEN")
//        minecraftVersions.add("1.21.1")
//        requires("vdjF5PL5") //dt
//        requires("MdwFAVRL") //cobblemon
//    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
